version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_BITIO_NAME=ssemlitz/fishcollector
      - POSTGRES_BITIO_USER=ssemlitz
      - POSTGRES_BITIO_PASSWORD=v2_3xSkg_bxptp7xiXZSnwFa3aqhRLrf
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_BITIO_NAME=ssemlitz/fishcollector
      - POSTGRES_BITIO_USER=ssemlitz
      - POSTGRES_BITIO_PASSWORD=v2_3xSkg_bxptp7xiXZSnwFa3aqhRLrf
    depends_on:
      - db